package com.floorspace.venus.enums;

public enum FloorSpaceConstructionType {

	FLOOR_HOUSE_CONSTRUCTION,
	STANDALONE_BUILDING_CONSTRUCTION,
	APARTMENT_CONSTRUCTION,
	SOCIETY_CONSTRUCTION,
	DIVIDE_PLOTS_CONSTRUCTION
}
